name: CI

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore Interview.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build with MSBuild
      run: msbuild  Interview.sln -p:Configuration=Release
    - name: Setup VSTest.exe
      uses: Malcolmnixon/Setup-VSTest@v2
    - name: Run Tests
      run: vstest.console Interview.Tests\bin\Release\Interview.Tests.dll
